// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: fridge.proto

package fridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToOpen        bool                   `protobuf:"varint,1,opt,name=to_open,json=toOpen,proto3" json:"to_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_fridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetToOpen() bool {
	if x != nil {
		return x.ToOpen
	}
	return false
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        bool                   `protobuf:"varint,1,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_fridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToClose       bool                   `protobuf:"varint,1,opt,name=to_close,json=toClose,proto3" json:"to_close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_fridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{2}
}

func (x *CloseRequest) GetToClose() bool {
	if x != nil {
		return x.ToClose
	}
	return false
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsClosed      bool                   `protobuf:"varint,1,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_fridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{3}
}

func (x *CloseResponse) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	DateAdded     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date_added,json=dateAdded,proto3" json:"date_added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_fridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Product) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Product) GetDateAdded() *timestamppb.Timestamp {
	if x != nil {
		return x.DateAdded
	}
	return nil
}

type AddProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_fridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{5}
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AddProductRequest) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_fridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProductRequest) Reset() {
	*x = RemoveProductRequest{}
	mi := &file_fridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProductRequest) ProtoMessage() {}

func (x *RemoveProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProductRequest.ProtoReflect.Descriptor instead.
func (*RemoveProductRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IsExpiredProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExpiredProductRequest) Reset() {
	*x = IsExpiredProductRequest{}
	mi := &file_fridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExpiredProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExpiredProductRequest) ProtoMessage() {}

func (x *IsExpiredProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExpiredProductRequest.ProtoReflect.Descriptor instead.
func (*IsExpiredProductRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{8}
}

func (x *IsExpiredProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IsExpiredProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExpired     bool                   `protobuf:"varint,1,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"`
	Product       *Product               `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	DaysRemaining int64                  `protobuf:"varint,3,opt,name=days_remaining,json=daysRemaining,proto3" json:"days_remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExpiredProductResponse) Reset() {
	*x = IsExpiredProductResponse{}
	mi := &file_fridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExpiredProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExpiredProductResponse) ProtoMessage() {}

func (x *IsExpiredProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExpiredProductResponse.ProtoReflect.Descriptor instead.
func (*IsExpiredProductResponse) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{9}
}

func (x *IsExpiredProductResponse) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

func (x *IsExpiredProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *IsExpiredProductResponse) GetDaysRemaining() int64 {
	if x != nil {
		return x.DaysRemaining
	}
	return 0
}

type ExpiringProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DaysThreshold int32                  `protobuf:"varint,1,opt,name=days_threshold,json=daysThreshold,proto3" json:"days_threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpiringProductsRequest) Reset() {
	*x = ExpiringProductsRequest{}
	mi := &file_fridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpiringProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpiringProductsRequest) ProtoMessage() {}

func (x *ExpiringProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpiringProductsRequest.ProtoReflect.Descriptor instead.
func (*ExpiringProductsRequest) Descriptor() ([]byte, []int) {
	return file_fridge_proto_rawDescGZIP(), []int{10}
}

func (x *ExpiringProductsRequest) GetDaysThreshold() int32 {
	if x != nil {
		return x.DaysThreshold
	}
	return 0
}

var File_fridge_proto protoreflect.FileDescriptor

const file_fridge_proto_rawDesc = "" +
	"\n" +
	"\ffridge.proto\x12\x06fridge\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"&\n" +
	"\vOpenRequest\x12\x17\n" +
	"\ato_open\x18\x01 \x01(\bR\x06toOpen\"'\n" +
	"\fOpenResponse\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\")\n" +
	"\fCloseRequest\x12\x19\n" +
	"\bto_close\x18\x01 \x01(\bR\atoClose\",\n" +
	"\rCloseResponse\x12\x1b\n" +
	"\tis_closed\x18\x01 \x01(\bR\bisClosed\"\xdd\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12;\n" +
	"\vexpiry_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x129\n" +
	"\n" +
	"date_added\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdateAdded\"\x9c\x01\n" +
	"\x11AddProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12;\n" +
	"\vexpiry_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"&\n" +
	"\x14RemoveProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\x17IsExpiredProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x8b\x01\n" +
	"\x18IsExpiredProductResponse\x12\x1d\n" +
	"\n" +
	"is_expired\x18\x01 \x01(\bR\tisExpired\x12)\n" +
	"\aproduct\x18\x02 \x01(\v2\x0f.fridge.ProductR\aproduct\x12%\n" +
	"\x0edays_remaining\x18\x03 \x01(\x03R\rdaysRemaining\"@\n" +
	"\x17ExpiringProductsRequest\x12%\n" +
	"\x0edays_threshold\x18\x01 \x01(\x05R\rdaysThreshold2\x9c\x04\n" +
	"\rFridgeService\x127\n" +
	"\n" +
	"OpenFridge\x12\x13.fridge.OpenRequest\x1a\x14.fridge.OpenResponse\x12:\n" +
	"\vCloseFridge\x12\x14.fridge.CloseRequest\x1a\x15.fridge.CloseResponse\x128\n" +
	"\n" +
	"AddProduct\x12\x19.fridge.AddProductRequest\x1a\x0f.fridge.Product\x128\n" +
	"\n" +
	"GetProduct\x12\x19.fridge.GetProductRequest\x1a\x0f.fridge.Product\x129\n" +
	"\fListProducts\x12\x16.google.protobuf.Empty\x1a\x0f.fridge.Product0\x01\x12E\n" +
	"\rRemoveProduct\x12\x1c.fridge.RemoveProductRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x10IsExpiredProduct\x12\x1f.fridge.IsExpiredProductRequest\x1a .fridge.IsExpiredProductResponse\x12I\n" +
	"\x13GetExpiringProducts\x12\x1f.fridge.ExpiringProductsRequest\x1a\x0f.fridge.Product0\x01B\x1fZ\x1ddanielches.fridge.v1;fridgev1b\x06proto3"

var (
	file_fridge_proto_rawDescOnce sync.Once
	file_fridge_proto_rawDescData []byte
)

func file_fridge_proto_rawDescGZIP() []byte {
	file_fridge_proto_rawDescOnce.Do(func() {
		file_fridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fridge_proto_rawDesc), len(file_fridge_proto_rawDesc)))
	})
	return file_fridge_proto_rawDescData
}

var file_fridge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_fridge_proto_goTypes = []any{
	(*OpenRequest)(nil),              // 0: fridge.OpenRequest
	(*OpenResponse)(nil),             // 1: fridge.OpenResponse
	(*CloseRequest)(nil),             // 2: fridge.CloseRequest
	(*CloseResponse)(nil),            // 3: fridge.CloseResponse
	(*Product)(nil),                  // 4: fridge.Product
	(*AddProductRequest)(nil),        // 5: fridge.AddProductRequest
	(*GetProductRequest)(nil),        // 6: fridge.GetProductRequest
	(*RemoveProductRequest)(nil),     // 7: fridge.RemoveProductRequest
	(*IsExpiredProductRequest)(nil),  // 8: fridge.IsExpiredProductRequest
	(*IsExpiredProductResponse)(nil), // 9: fridge.IsExpiredProductResponse
	(*ExpiringProductsRequest)(nil),  // 10: fridge.ExpiringProductsRequest
	(*timestamppb.Timestamp)(nil),    // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_fridge_proto_depIdxs = []int32{
	11, // 0: fridge.Product.expiry_date:type_name -> google.protobuf.Timestamp
	11, // 1: fridge.Product.date_added:type_name -> google.protobuf.Timestamp
	11, // 2: fridge.AddProductRequest.expiry_date:type_name -> google.protobuf.Timestamp
	4,  // 3: fridge.IsExpiredProductResponse.product:type_name -> fridge.Product
	0,  // 4: fridge.FridgeService.OpenFridge:input_type -> fridge.OpenRequest
	2,  // 5: fridge.FridgeService.CloseFridge:input_type -> fridge.CloseRequest
	5,  // 6: fridge.FridgeService.AddProduct:input_type -> fridge.AddProductRequest
	6,  // 7: fridge.FridgeService.GetProduct:input_type -> fridge.GetProductRequest
	12, // 8: fridge.FridgeService.ListProducts:input_type -> google.protobuf.Empty
	7,  // 9: fridge.FridgeService.RemoveProduct:input_type -> fridge.RemoveProductRequest
	8,  // 10: fridge.FridgeService.IsExpiredProduct:input_type -> fridge.IsExpiredProductRequest
	10, // 11: fridge.FridgeService.GetExpiringProducts:input_type -> fridge.ExpiringProductsRequest
	1,  // 12: fridge.FridgeService.OpenFridge:output_type -> fridge.OpenResponse
	3,  // 13: fridge.FridgeService.CloseFridge:output_type -> fridge.CloseResponse
	4,  // 14: fridge.FridgeService.AddProduct:output_type -> fridge.Product
	4,  // 15: fridge.FridgeService.GetProduct:output_type -> fridge.Product
	4,  // 16: fridge.FridgeService.ListProducts:output_type -> fridge.Product
	12, // 17: fridge.FridgeService.RemoveProduct:output_type -> google.protobuf.Empty
	9,  // 18: fridge.FridgeService.IsExpiredProduct:output_type -> fridge.IsExpiredProductResponse
	4,  // 19: fridge.FridgeService.GetExpiringProducts:output_type -> fridge.Product
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_fridge_proto_init() }
func file_fridge_proto_init() {
	if File_fridge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fridge_proto_rawDesc), len(file_fridge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fridge_proto_goTypes,
		DependencyIndexes: file_fridge_proto_depIdxs,
		MessageInfos:      file_fridge_proto_msgTypes,
	}.Build()
	File_fridge_proto = out.File
	file_fridge_proto_goTypes = nil
	file_fridge_proto_depIdxs = nil
}
